-- USER
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD) VALUES (1, 'user', 'user');

-- AUTHOR
INSERT INTO AUTHOR (AUTHOR_ID, NAME) VALUES (1, 'wtml');
INSERT INTO AUTHOR (AUTHOR_ID, NAME) VALUES (2, 'kf');

-- BOOK


-- BOOKING