FROM openjdk:15
LABEL maintainer="javaguides.net"
ADD target/bookingbook-0.0.1-SNAPSHOT.jar bookingbook-0.0.1-SNAPSHOT.jar.original
ENTRYPOINT ["java", "-jar", "bookingbook-0.0.1-SNAPSHOT.jar.original"]